version: '3.8'
services:
  web:
    build: .
    container_name: pulsefit-web
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=supersecretkey
    entrypoint: ["/app/wait-for-db.sh", "db", "python", "app.py"]
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: pulsefit-db
    environment:
      POSTGRES_USER: pulsefit
      POSTGRES_PASSWORD: pulsefitpass
      POSTGRES_DB: pulsefit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
